#!/usr/bin/python

import os
import sys
import re

# compile with ROOT, Geant4, MySQL and BOOST
def compile(filename):
	## ROOT part
    cflags = os.popen('root-config --cflags').readline().strip()
    ldflags = os.popen('root-config --ldflags --libs').readline().strip()

    ## Geant part
    cflags = cflags + ' ' + os.popen('geant4-config --cflags').readline().strip()
    ldflags = ldflags + ' ' + os.popen('geant4-config --libs').readline().strip()

    ## BOOST part
    cflags = cflags + ' -I' + os.environ['BOOST']

    ## MySQL part
    cflags = cflags + ' -I' + os.environ['MYSQL_INCLUDE']
    ldflags = ldflags + ' -lz -L'+os.environ['MYSQL_LIB'] + ' -lmysqlclient'

    ## kTracker part
    ldflags = ldflags + ' -L$KTRACKER_LIB -lkTracker'

    os.system('g++ '+cflags+' -c '+filename+'.cxx')
    os.system('g++ -o '+filename+' '+filename+'.o '+ldflags)
    os.system('rm '+filename+'.o')

# make sure it exists
if not os.path.isfile(sys.argv[1].replace('.cxx', '')+'.cxx'):
    print 'File does not exist!'
    sys.exit(1)

# extract the path and source file name
args = re.split('/', sys.argv[1])
targetName = args[-1].replace('.cxx', '')
sourceName = targetName + '.cxx'
sourcePath = sys.argv[1].replace('.cxx', '').replace(targetName, '')

# copy the source file to KTRACKER_ROOT, compile an delete it afterwards
if len(args) == 1 or (len(args) == 2 and args[0] == '.'):
    compile(targetName)
elif os.path.isfile(sourceName):
    print 'File already exists in both KTRACKER_ROOT and '+sys.argv[1].replace(sourceName, '')+'!! Please check.'
else:
    os.system('cp '+sourcePath+'/'+sourceName+' '+sourceName)
    compile(targetName)
    os.system('rm '+sourceName)
